default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: <%= ENV['MYSQL_PASS'] %>
  socket: <%= ENV['MYSQL_SOCKET'] %>
  # template: template0

development:
  <<: *default
  database: achieve_development

test:
  <<: *default
  database: achieve_test

production:
  <<: *default
  database: achieve_production
